from __future__ import annotations

import json
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass
from functools import lru_cache
from typing import TYPE_CHECKING, Any
from urllib import error, request

from fastapi import HTTPException

from backend.config import RAG_API_BASE_URL
from backend.modules.agent.llm import get_agent_llm
from backend.modules.agent.schemas import ToolSpec

if TYPE_CHECKING:
    from backend.modules.agent.memory import ConversationTurn


class RagApiClient:
    def __init__(self, base_url: str | None = None, opener=None) -> None:
        self._base_url = (base_url or RAG_API_BASE_URL).rstrip("/")
        self._opener = opener or request.urlopen

    def retrieve(self, query: str, top_k: int = 3) -> list[dict[str, Any]]:
        payload = json.dumps({"query": query, "top_k": top_k}).encode("utf-8")
        http_request = request.Request(
            f"{self._base_url}/rag/retrieve",
            data=payload,
            headers={"Content-Type": "application/json", "accept": "application/json"},
            method="POST",
        )

        try:
            with self._opener(http_request, timeout=60) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except error.URLError as exc:
            raise HTTPException(
                status_code=503,
                detail=f"RAG API is unavailable at {self._base_url}. Start the backend before using the agent.",
            ) from exc

        if not response_payload.get("success", False):
            raise HTTPException(status_code=502, detail="RAG API returned an error")

        data = response_payload.get("data", {})
        return list(data.get("documents", []))

    def ask(self, question: str, top_k: int = 3) -> dict[str, Any]:
        payload = json.dumps({"question": question, "top_k": top_k}).encode("utf-8")
        http_request = request.Request(
            f"{self._base_url}/rag/ask",
            data=payload,
            headers={"Content-Type": "application/json", "accept": "application/json"},
            method="POST",
        )

        try:
            with self._opener(http_request, timeout=60) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except error.URLError as exc:
            raise HTTPException(
                status_code=503,
                detail=f"RAG API is unavailable at {self._base_url}. Start the backend before using the agent.",
            ) from exc

        if not response_payload.get("success", False):
            raise HTTPException(status_code=502, detail="RAG API returned an error")

        return dict(response_payload.get("data", {}))


@lru_cache(maxsize=1)
def get_rag_api_client() -> RagApiClient:
    return RagApiClient()


class AgentTool(ABC):
    spec: ToolSpec

    @abstractmethod
    def run(self, message: str, top_k: int = 3, history: list[ConversationTurn] | None = None) -> dict[str, Any]:
        raise NotImplementedError


@dataclass(slots=True)
class SearchDocumentsTool(AgentTool):
    rag_client: RagApiClient
    spec: ToolSpec = ToolSpec(
        name="search_docs",
        description="Answer a question using the RAG answer API.",
        input_schema='{"message": "string", "top_k": 3}',
        output_schema='{"answer": "string", "sources": [], "retrieved_documents": 0}',
    )

    def run(self, message: str, top_k: int = 3, history: list[ConversationTurn] | None = None) -> dict[str, Any]:
        result = self.rag_client.ask(message, top_k=top_k)
        return {
            **result,
            "generation_mode": "rag_llm",
            "generation_reason": "Answer generated by the RAG answer pipeline",
            "ollama_response": None,
        }


@dataclass(slots=True)
class SummarizeTool(AgentTool):
    rag_client: RagApiClient
    spec: ToolSpec = ToolSpec(
        name="summarize",
        description="Summarize retrieved document chunks into a short study note.",
        input_schema='{"message": "string", "top_k": 3}',
        output_schema='{"summary": "string", "sources": []}',
    )

    def run(self, message: str, top_k: int = 3, history: list[ConversationTurn] | None = None) -> dict[str, Any]:
        documents = self.rag_client.retrieve(message, top_k=top_k)
        if not documents:
            return {
                "summary": "I don't know.",
                "sources": [],
                "retrieved_documents": 0,
                "generation_mode": "fallback",
                "generation_reason": "No documents were retrieved",
                "ollama_response": None,
            }

        combined_text = self._combine_text(documents)
        summary, generation_mode, generation_reason, ollama_response = self._generate_summary_with_llm(message, combined_text)

        return {
            "summary": summary,
            "sources": self._build_sources(documents),
            "retrieved_documents": len(documents),
            "generation_mode": generation_mode,
            "generation_reason": generation_reason,
            "ollama_response": ollama_response,
        }

    def _combine_text(self, documents: list[dict[str, Any]]) -> str:
        return " ".join(document.get("text", "") for document in documents if document.get("text"))

    def _generate_summary_with_llm(self, message: str, text: str) -> tuple[str, str, str, str | None]:
        llm = get_agent_llm()
        
        prompt = f"""Create a concise summary of the following text based on the user's request.

User request: {message}

Text:
{text}

Provide a clear, well-structured summary that captures the main points."""

        try:
            response = llm.answer(prompt)
            summary = response.strip() if response else ""
            if summary:
                return summary, "llm", "Generated by Ollama", response
        except Exception:
            sentences = self._split_sentences(text)
            fallback_summary = " ".join(sentences[:2]) if sentences else "I don't know."
            return fallback_summary, "fallback", "Ollama timed out or was unavailable", None

        sentences = self._split_sentences(text)
        fallback_summary = " ".join(sentences[:2]) if sentences else "I don't know."
        return fallback_summary, "fallback", "LLM returned an empty response", response

    def _build_sources(self, documents: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [
            {
                "chunk_number": index,
                "metadata": document.get("metadata", {}),
                "distance": document.get("distance"),
                "score": document.get("score"),
            }
            for index, document in enumerate(documents, start=1)
        ]

    def _split_sentences(self, text: str) -> list[str]:
        parts = re.split(r"(?<=[.!?])\s+", text.strip())
        return [part.strip() for part in parts if part.strip()]


@dataclass(slots=True)
class QuizTool(AgentTool):
    rag_client: RagApiClient
    spec: ToolSpec = ToolSpec(
        name="quiz",
        description="Create multiple-choice questions from retrieved notes.",
        input_schema='{"message": "string", "top_k": 3}',
        output_schema='{"quiz": [{"question": "string", "choices": [], "answer": "string"}]}',
    )

    def run(self, message: str, top_k: int = 3, history: list[ConversationTurn] | None = None) -> dict[str, Any]:
        documents = self.rag_client.retrieve(message, top_k=top_k)
        if not documents:
            return {
                "quiz": [],
                "sources": [],
                "retrieved_documents": 0,
                "generation_mode": "fallback",
                "generation_reason": "No documents were retrieved",
                "ollama_response": None,
            }

        combined_text = self._combine_text(documents)
        quiz, generation_mode, generation_reason, ollama_response = self._generate_quiz_with_llm(message, combined_text)

        return {
            "quiz": quiz,
            "sources": self._build_sources(documents),
            "retrieved_documents": len(documents),
            "generation_mode": generation_mode,
            "generation_reason": generation_reason,
            "ollama_response": ollama_response,
        }

    def _combine_text(self, documents: list[dict[str, Any]]) -> str:
        return " ".join(document.get("text", "") for document in documents if document.get("text"))

    def _generate_quiz_with_llm(self, message: str, text: str) -> tuple[list[dict[str, Any]], str, str, str | None]:
        llm = get_agent_llm()
        
        prompt = f"""Create 3 multiple-choice questions based on the following text.

User request: {message}

Text:
{text}

Return ONLY a JSON array with this format:
[
  {{
    "question": "question text",
    "choices": ["option1", "option2", "option3", "option4"],
    "answer": "correct option"
  }}
]

Make questions challenging but fair based on the provided text."""

        try:
            response = llm.answer(prompt)
            parsed = self._parse_quiz_response(response)
            if parsed:
                return parsed, "llm", "Generated by Ollama", response
        except Exception:
            pass

        return self._generate_fallback_quiz(text), "fallback", "Ollama timed out or was unavailable", None

    def _parse_quiz_response(self, response: str) -> list[dict[str, Any]]:
        json_match = re.search(r'\[.*\]', response, re.DOTALL)
        if not json_match:
            return []
        
        try:
            quiz_data = json.loads(json_match.group())
            if not isinstance(quiz_data, list):
                return []
            
            validated_quiz = []
            for item in quiz_data[:3]:
                if isinstance(item, dict) and "question" in item and "choices" in item and "answer" in item:
                    validated_quiz.append({
                        "question": item["question"],
                        "choices": item["choices"],
                        "answer": item["answer"]
                    })
            
            return validated_quiz
        except json.JSONDecodeError:
            return []

    def _generate_fallback_quiz(self, text: str) -> list[dict[str, Any]]:
        sentences = self._split_sentences(text)
        if not sentences:
            return []

        base = sentences[0].rstrip(".")
        return [
            {
                "question": f"What is the main idea in the retrieved notes about {self._keyword_from_text(text)}?",
                "choices": [base, "Unrelated concept", "Opposite idea", "Random detail"],
                "answer": base,
            }
        ]

    def _keyword_from_text(self, text: str) -> str:
        words = re.findall(r"[A-Za-z][A-Za-z\-]{4,}", text)
        return words[0].lower() if words else "the topic"

    def _split_sentences(self, text: str) -> list[str]:
        parts = re.split(r"(?<=[.!?])\s+", text.strip())
        return [part.strip() for part in parts if part.strip()]

    def _build_sources(self, documents: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [
            {
                "chunk_number": index,
                "metadata": document.get("metadata", {}),
                "distance": document.get("distance"),
                "score": document.get("score"),
            }
            for index, document in enumerate(documents, start=1)
        ]


@dataclass(slots=True)
class FlashcardTool(AgentTool):
    rag_client: RagApiClient
    spec: ToolSpec = ToolSpec(
        name="flashcards",
        description="Create question-answer flashcards from retrieved notes.",
        input_schema='{"message": "string", "top_k": 3}',
        output_schema='{"flashcards": [{"front": "string", "back": "string"}]}',
    )

    def run(self, message: str, top_k: int = 3, history: list[ConversationTurn] | None = None) -> dict[str, Any]:
        documents = self.rag_client.retrieve(message, top_k=top_k)
        if not documents:
            return {
                "flashcards": [],
                "sources": [],
                "retrieved_documents": 0,
                "generation_mode": "fallback",
                "generation_reason": "No documents were retrieved",
                "ollama_response": None,
            }

        combined_text = self._combine_text(documents)
        flashcards, generation_mode, generation_reason, ollama_response = self._generate_flashcards_with_llm(message, combined_text)

        return {
            "flashcards": flashcards,
            "sources": self._build_sources(documents),
            "retrieved_documents": len(documents),
            "generation_mode": generation_mode,
            "generation_reason": generation_reason,
            "ollama_response": ollama_response,
        }

    def _combine_text(self, documents: list[dict[str, Any]]) -> str:
        return " ".join(document.get("text", "") for document in documents if document.get("text"))

    def _generate_flashcards_with_llm(self, message: str, text: str) -> tuple[list[dict[str, Any]], str, str, str | None]:
        llm = get_agent_llm()
        
        prompt = f"""Create 5 high-quality question-answer flashcards based on the following text.

User request: {message}

Text:
{text}

Return ONLY a JSON array with this format:
[
  {{
    "front": "question",
    "back": "answer"
  }}
]

Make questions clear and answers concise but comprehensive based on the provided text."""

        try:
            response = llm.answer(prompt)
            parsed = self._parse_flashcard_response(response)
            if parsed:
                return parsed, "llm", "Generated by Ollama", response
        except Exception:
            pass

        return self._generate_fallback_flashcards(text), "fallback", "Ollama timed out or was unavailable", None

    def _parse_flashcard_response(self, response: str) -> list[dict[str, Any]]:
        json_match = re.search(r'\[.*\]', response, re.DOTALL)
        if not json_match:
            return []
        
        try:
            flashcard_data = json.loads(json_match.group())
            if not isinstance(flashcard_data, list):
                return []
            
            validated_flashcards = []
            for item in flashcard_data[:5]:
                if isinstance(item, dict) and "front" in item and "back" in item:
                    validated_flashcards.append({
                        "front": item["front"],
                        "back": item["back"]
                    })
            
            return validated_flashcards
        except json.JSONDecodeError:
            return []

    def _generate_fallback_flashcards(self, text: str) -> list[dict[str, Any]]:
        sentences = self._split_sentences(text)
        if not sentences:
            return []

        return [
            {
                "front": f"What is stated in chunk {index}?",
                "back": sentence,
            }
            for index, sentence in enumerate(sentences[:3], start=1)
        ]

    def _split_sentences(self, text: str) -> list[str]:
        parts = re.split(r"(?<=[.!?])\s+", text.strip())
        return [part.strip() for part in parts if part.strip()]

    def _build_sources(self, documents: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [
            {
                "chunk_number": index,
                "metadata": document.get("metadata", {}),
                "distance": document.get("distance"),
                "score": document.get("score"),
            }
            for index, document in enumerate(documents, start=1)
        ]


def build_default_tools() -> dict[str, AgentTool]:
    rag_client = get_rag_api_client()
    return {
        "search_docs": SearchDocumentsTool(rag_client),
        "summarize": SummarizeTool(rag_client),
        "quiz": QuizTool(rag_client),
        "flashcards": FlashcardTool(rag_client),
    }
